---
abstract: 'scrypt support for DBIx::Class::EncodedColumn'
author:
  - 'Forest Belton <forest@homolo.gy>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-EncodedColumn-Crypt-Scrypt
requires:
  Crypt::ScryptKDF: 0.008
  DBIx::Class::EncodedColumn: 0.00012
  Dir::Self: 0.11
  File::Spec: 3.40
  Test::Simple: 1.001002
version: 0.001
